#!/usr/bin/env python3
"""Render original VoxPet geometric cat sprites. Dev-only dependency: Pillow."""
from pathlib import Path
import json
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / "src/VoxPet.App/Assets/Characters"
TARGET.mkdir(parents=True, exist_ok=True)
# 3배 해상도로 도형을 그린 뒤 축소해 512px PNG의 경계를 부드럽게 만든다.
SCALE = 3

# 몸/발 anchor는 모든 상태에서 같고 눈과 입 도형만 달라진다. 외부 이미지를 사용하지 않는다.
def sprite(mouth, blink, expression="neutral"):
    im = Image.new("RGBA", (512 * SCALE, 512 * SCALE))
    d = ImageDraw.Draw(im)
    def coords(box): return tuple(int(v * SCALE) for v in box)
    def ellipse(box, fill, outline=None, width=4): d.ellipse(coords(box), fill, outline, width * SCALE)
    def polygon(points, fill): d.polygon([(int(x*SCALE), int(y*SCALE)) for x,y in points], fill)
    def line(points, fill, width=4): d.line([(int(x*SCALE), int(y*SCALE)) for x,y in points], fill, width*SCALE)
    ink, fur, light = "#28364C", "#BFA7F1", "#F0E7FA"
    # 꼬리·발·몸·귀·머리 좌표를 모든 상태에서 공유해 PNG 전환 시 캐릭터가 튀지 않게 한다.
    d.arc(coords((302,280,450,443)), 230, 520, fill=ink, width=32*SCALE)
    d.arc(coords((302,280,450,443)), 230, 520, fill=fur, width=23*SCALE)
    ellipse((143,382,243,465), fur, ink); ellipse((271,382,371,465), fur, ink)
    ellipse((148,235,365,451), fur, ink)
    ellipse((186,302,325,434), light)
    polygon([(113,192),(117,55),(225,133)], ink); polygon([(287,133),(396,55),(399,192)], ink)
    polygon([(127,176),(129,78),(211,137)], fur); polygon([(303,137),(384,78),(385,176)], fur)
    polygon([(143,148),(144,102),(186,139)], "#E8AAC4"); polygon([(327,139),(370,102),(369,148)], "#E8AAC4")
    ellipse((98,108,414,338), fur, ink)
    ellipse((137,250,192,279), "#E8AAC4"); ellipse((320,250,375,279), "#E8AAC4")
    if blink or expression == "sleepy":
        line([(171,228),(189,234),(207,228)], ink, 6); line([(305,228),(323,234),(341,228)], ink, 6)
    elif expression == "happy":
        d.arc(coords((171,213,207,247)), 195, 345, fill=ink, width=6*SCALE)
        d.arc(coords((305,213,341,247)), 195, 345, fill=ink, width=6*SCALE)
    else:
        eye_height = 43 if expression == "surprised" else 34
        ellipse((177,210,197,210+eye_height), ink); ellipse((315,210,335,210+eye_height), ink)
        ellipse((181,214,187,222), "white", width=0); ellipse((319,214,325,222), "white", width=0)
    if expression == "sad":
        line([(170,204),(206,193)], ink, 5); line([(305,193),(341,204)], ink, 5)
    elif expression == "angry":
        line([(170,191),(206,204)], ink, 5); line([(305,204),(341,191)], ink, 5)
    elif expression == "surprised":
        d.arc(coords((168,186,210,205)), 190, 350, fill=ink, width=4*SCALE)
        d.arc(coords((302,186,344,205)), 190, 350, fill=ink, width=4*SCALE)
    polygon([(246,243),(266,243),(256,253)], ink)
    if mouth == "closed" and expression == "sad":
        d.arc(coords((237,263,276,290)), 195, 345, fill=ink, width=4*SCALE)
    elif mouth == "closed" and expression == "surprised":
        ellipse((247,261,265,282), ink)
    elif mouth == "closed" and expression == "happy":
        d.arc(coords((231,247,281,276)), 5, 175, fill=ink, width=4*SCALE)
    elif mouth == "closed":
        d.arc(coords((236,244,257,266)), 0, 155, fill=ink, width=4*SCALE)
        d.arc(coords((256,244,277,266)), 25, 180, fill=ink, width=4*SCALE)
    else:
        height = 21 if mouth == "half" else 48
        ellipse((235,258,277,258+height), ink)
        ellipse((244,258+height*.58,269,257+height), "#F0A0B8", width=0)
    for side in (-1,1):
        line([(256+side*91,261),(256+side*134,252)], ink, 3)
        line([(256+side*91,276),(256+side*136,282)], ink, 3)
    ellipse((181,311,219,345), fur, ink); ellipse((293,311,331,345), fur, ink)
    return im.resize((512,512), Image.Resampling.LANCZOS)

# 개발용 재생성 명령은 기존 PNG 6장과 manifest를 덮어쓴다. 일반 빌드/앱 실행에는 호출하지 않는다.
for mouth in ("closed", "half", "open"):
    for blink in (False, True):
        sprite(mouth, blink).save(TARGET / f"{mouth}{'-blink' if blink else ''}.png")
manifest = {"name":"Violet Cat", "size":[512,512], "anchor":[256,465], "states":[f"{m}{b}.png" for m in ("closed","half","open") for b in ("","-blink")], "source":"Original geometric artwork generated by harness/scripts/generate_character.py for VoxPet", "license":"CC0-1.0", "licenseUrl":"https://creativecommons.org/publicdomain/zero/1.0/", "attributionRequired":False}
(TARGET / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
# 기본 여섯 상태는 그대로 유지하고 같은 anchor의 표정 변형을 추가한다.
expressions = ["happy", "sad", "angry", "surprised", "sleepy"]
for expression in expressions:
    for mouth in ("closed", "half", "open"):
        for blink in (False, True):
            sprite(mouth, blink, expression).save(TARGET / f"{expression}-{mouth}{'-blink' if blink else ''}.png")
manifest["expressions"] = {expression: [f"{expression}-{m}{b}.png" for m in ("closed", "half", "open") for b in ("", "-blink")] for expression in expressions}
(TARGET / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
print("Generated 36 original 512×512 transparent PNG states")
